sudo: required
services:
  - docker

before_install:
  - docker build -t kjelltore/react-test -f ./client/Dockerfile.dev ./client
 
script:
  - docker run -e CI=true kjelltore/react-test npm test

after_success:
  - docker build -t kjelltore/multi-client ./client
  - docker build -t kjelltore/multi-nginx ./nginx
  - docker build -t kjelltore/multi-server ./server
  - docker build -t kjelltore/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kjelltore/multi-client
  - docker push kjelltore/multi-nginx
  - docker push kjelltore/multi-server
  - docker push kjelltore/multi-worker
